# Generated by Django 4.1.7 on 2023-03-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_feedback_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=200)),
                ('college', models.CharField(max_length=120)),
                ('year', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
