# Generated by Django 4.1.7 on 2023-03-05 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_customer_alter_feedback_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='fname',
        ),
    ]
