# Generated by Django 4.1.7 on 2023-03-17 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_menu'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
