# Generated by Django 4.1.7 on 2023-03-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_delete_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food1', models.CharField(max_length=255)),
                ('food2', models.CharField(max_length=255)),
                ('food3', models.CharField(max_length=255)),
                ('food4', models.CharField(max_length=255)),
                ('food5', models.CharField(max_length=255)),
                ('food6', models.CharField(max_length=255)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
