# Generated by Django 4.1.7 on 2023-04-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_rename_date_attendance_date_in'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
